#if !canImport(ObjectiveC)
import XCTest

extension ParameterLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParameterLoaderTests = [
        ("testEmptyArgumentListShallBeFaulty", testEmptyArgumentListShallBeFaulty),
        ("testMixedArgumentsWithLeadingOptionShouldSuccess", testMixedArgumentsWithLeadingOptionShouldSuccess),
        ("testMixedArgumentsWithLeadingValuesShouldSuccess", testMixedArgumentsWithLeadingValuesShouldSuccess),
        ("testMultipleUnnamedValuesShouldSuccess", testMultipleUnnamedValuesShouldSuccess),
        ("testOptionAndValueShouldSuccess", testOptionAndValueShouldSuccess),
        ("testSingleArgumentShallResultInEmptyParameters", testSingleArgumentShallResultInEmptyParameters),
        ("testSingleFlagShouldSuccess", testSingleFlagShouldSuccess),
        ("testTwoSequentialFlagsShouldSuccess", testTwoSequentialFlagsShouldSuccess),
        ("testUnnamedValueShouldSuccess", testUnnamedValueShouldSuccess),
        ("testUnrecognizedOptionShallBeFaulty", testUnrecognizedOptionShallBeFaulty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParameterLoaderTests.__allTests__ParameterLoaderTests),
    ]
}
#endif
